import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Header from "./component/header";
import Footer from "./component/footer";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { api } from "./apis/apiList";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Unipulse",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  // categories fetch karo
  const res = await fetch(api.apiCall.categoryList, { cache: "no-store" });
  const data = await res.json();
  const categories = data?.data || [];

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header categories={categories} />  {/* ✅ pass karo */}
        {children}
        <Footer />
        <ToastContainer
          position="top-center"
          autoClose={2000}
        />
      </body>
    </html>
  );
}


// import { Geist, Geist_Mono, Inter } from "next/font/google";
// import "./globals.css";
// import Header from "./component/header";
// import Footer from "./component/footer";
// import { ToastContainer } from 'react-toastify';     
// import 'react-toastify/dist/ReactToastify.css';       

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const inter = Inter({
//   variable: "--font-inter",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Unipulse",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">
//         <Header/>
//         {children}
//         <Footer/>
//        <ToastContainer 
//     position="top-center"  
//     autoClose={2000} 
// />
//       </body>
//     </html>
//   );
// }